# Generated by Django 2.1.4 on 2019-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_header', models.CharField(max_length=200)),
                ('article_time', models.DateTimeField(verbose_name='pub time')),
            ],
        ),
        migrations.CreateModel(
            name='ShortArtical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortartical_contain', models.CharField(max_length=500)),
                ('shortartical_time', models.DateTimeField(verbose_name='shortpub time')),
            ],
        ),
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ip', models.CharField(max_length=100)),
                ('view_date', models.DateTimeField(verbose_name='view time')),
            ],
        ),
    ]
